---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      run: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: alessandrocavaglia/api-gateway
          ports:
            - containerPort: 8762
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    run: api-gateway
spec:
  type: NodePort
  ports:
    - port: 8762
      protocol: TCP
  selector:
    run: api-gateway